### ISSUE TITLE
Data: Missing links from non-death events to respective person

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#13]
Currently, `burial` / `declared missing` / `declared dead` events are built without any link to the resp. person. 

## Declared Missing / Declared Dead
Looks like:
```
<https://sk.acdh.oeaw.ac.at/DWpers0164/event/0> a cidoc:E5_Event ;
        rdfs:label "Event: Declared/Gone Missing"@und ;
        cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/missing> ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWpers0164/event/0/time-span> .
```
Should look like:
```
<https://sk.acdh.oeaw.ac.at/DWpers0164/event/0> a cidoc:E13_Attribute_Assignment ;
        rdfs:label "Declared/Gone Missing"@und ;
        cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/missing> ;
        cidoc:P140_assigned_attribute_to <https://sk.acdh.oeaw.ac.at/DWpers0164> ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWpers0164/event/0/time-span> .
```
So: 
- Change class declaration (line 1)
- Delete "Event: " from label (line 2)
- add line with P140. (line 4)
That's it.

## Burial
Looks like:
```
    <https://sk.acdh.oeaw.ac.at/DWpers1105/event/0> a cidoc:E5_Event ;
        rdfs:label "Event: Burial"@und ;
        cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/burial> ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWpers1105/event/0/time-span> ;
        cidoc:P7_took_place_at sk:DWplace00066 .
```
Just add this line with the respective person-URI:
`cidoc:P12_occurred_in_the_presence_of  <https://sk.acdh.oeaw.ac.at/DWpers1105> ;`
And maybe change the language tag (line 2) to "en".

**Comment by BOberreither** [comment]
@linxOD 
### Very minor things:
- [ ] shorten label:
```
<https://sk.acdh.oeaw.ac.at/DWpers0060/event/1> a cidoc:E13_Attribute_Assignment ;
        rdfs:label "Event type: Declared Dead"@en ;
        cidoc:P140_assigned_attribute_to sk:DWpers0060 ;
        cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/decl-dead> ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWpers0060/event/1/time-span> .
```
Please change label to "Declared Dead" only.
- [x] Same with Event type Burial.

**Comment by linxOD** [comment]
> @linxOD
> 
> ### Very minor things:
> * [ ]  shorten label:
> 
> ```
> <https://sk.acdh.oeaw.ac.at/DWpers0060/event/1> a cidoc:E13_Attribute_Assignment ;
>         rdfs:label "Event type: Declared Dead"@en ;
>         cidoc:P140_assigned_attribute_to sk:DWpers0060 ;
>         cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/decl-dead> ;
>         cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWpers0060/event/1/time-span> .
> ```

In this case "Event type: " is part of the data in indices/listper.xml. Should I still handle it or can it be removed from the data?
