### ISSUE TITLE
Bits and Pieces: data

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#15]
## Time-Span type approx
Many birht- or death-elements have a `@type="approx"`, in these cases please add this triple:
`cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx>`
to the respective time-span statement, just like in lk data. Thanks!

## Many owl:sameAs
E53_Place and E74_Group statements have `owl:sameAs` triples; please delete those (`sameAs` is reserved for inter-graph relations).

**Comment by linxOD** [comment]
types:approx were already handled e.g.:

```
<https://sk.acdh.oeaw.ac.at/DWpers0009/birth/time-span> a cidoc:E52_Time-Span ;
        rdfs:label "1770-12-16"^^xsd:string ;
        cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx> ;
        cidoc:P82a_begin_of_the_begin "1770-12-16"^^xsd:date ;
        cidoc:P82b_end_of_the_end "1770-12-16"^^xsd:date .
```
