### ISSUE TITLE
rdfs:label-o-rama

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#16]
### DW texts
- [x] F24 Periodical: Currently "Periodical: [Title]", please change to "[Title] (Periodical/Series)"
- [x] F24 Issue: Currently "Published Expression: Deutsche Allgemeine Zeitung", please change to: "Deutsche Allgemeine Zeitung (Published Issue)"
- [x] F22 Issue: Currently "Issue: Deutsche Allgemeine Zeitung", please change to: "Deutsche Allgemeine Zeitung (Issue)"
- [x] F22 of Non-Issues: Article, Monograph: Currently "Expression: Unsere Meinung" or "Expression: Abendlied", please reduce to title only: "Unsere Meinung", "Abendlied"
- [x] F24 of Non-Issues: Currently "Publication carrying ..." - perfect.

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe One question: The 4th checkbox, was it really done? In RS, the labels look like this:
[Expression: Briefe flüchtiger Nationalsozialisten](https://sk.acdh-dev.oeaw.ac.at/resource/?uri=https%3A%2F%2Fsk.acdh.oeaw.ac.at%2FDWbibl01286)

**Comment by BergListe** [comment]
As far as I remember this box was already checked, when I first opened this issue.

**Comment by BergListe** [comment]
Does this concern also `#F22 art-issue` statements?

like this one...
```rdf
#F22 art-issue
<https://sk.acdh.oeaw.ac.at/DWbibl04131> a frbroo:F22_Self-Contained_Expression ;
  rdfs:label "Expression: Wiener Chronik"@en ;
  cidoc:P102_has_title <https://sk.acdh.oeaw.ac.at/DWbibl04131/title/0> ;
  cidoc:P165i_is_incorporated_in <https://sk.acdh.oeaw.ac.at/DWbibl05093> .
```

**Comment by BOberreither** [comment]
Yes.

**Comment by BergListe** [comment]
Done
