### ISSUE TITLE
Minor: Change of two Type-URIs from "orig-name" to "pref"

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#17]
## placename
Please change
```
<https://sk.acdh.oeaw.ac.at/types/place/placename/orig-name>
```
to 
```
<https://sk.acdh.oeaw.ac.at/types/place/placename/pref>
```
## orgname
Please change
```
<https://sk.acdh.oeaw.ac.at/types/org/orgname/orig-name>
```
to 
```
<https://sk.acdh.oeaw.ac.at/types/org/orgname/pref>
```

(In both cases at object position as well as in their own statement.)
Thanks!

**Comment by linxOD** [comment]
~/orig-name is take from @type="orig_name" in listplace.xml and listorg.xml 
could this be changed in the data?
