### ISSUE TITLE
Values in INT3, line 3

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#19]
```
#INT3 intertext relationship
<https://sk.acdh.oeaw.ac.at/DWbibl01990/relation/2> a ns1:INT3_IntertextualRelationship  ;
  rdfs:label "Intertextual relation"@en ;
  ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at//passage/2> ;
  ns1:R13_has_referring_entity <https://sk.acdh.oeaw.ac.at/DWbibl01990/passage/2> .
```

- [ ] `ns1:R12_has_referred_to_entity` should have ID DWbibl04025 in URI
- [ ] Also: The [n] in the end seems to be the same in every case (here, "0" would be correct)

Desired outcome for this line: 
`ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/DWbibl04025/passage/0> ;`

- If in the citedRange/ref type int the @target refers to a target citedRange with `@wholeText="yes"`, then the xml:id of the target citedRange
- If in the citedRange/ref type int the @target refers to a target citedRange WITHOUT @wholeText="yes", then the parent::bibl/@xml:id of the target citedRange
- The number at the end indicates the position of the target citedRange in its bibl (currently it seems like it indicates - wrongly - the position of the source citedRange instead).

**Comment by BergListe** [comment]
Weirdly I cannot reproduce the problem. I debugged the xml:template that creates the above mentioned INT3 statement and I get the wanted result without any changes...
