### ISSUE TITLE
listbibl - empty values and labels at E42_Identifier

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#20]
For E42_identifiers ending in "identifier/idno/3>" and for E35_title ending in "/title/0>", rdfs:label and rdf:value are empty, please check xPath, thanks!

**Comment by BergListe** [comment]
Fixed. Two occurrences of  `rdf:value ""` are left - both are false positives due to empty `<title level="a" type="subtitle"/>` tags.
