### ISSUE TITLE
DW texts: change some F24 labels

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#25]
Does NOT concern:
- Periodical-F24s built from title j keys
- Issue-F24s built from date keys
- F24s built from title m keys.

Does concern:
- **F24s built from wholeText-citedRange/xml:id**
- F24s built from bibl xml:ids
Please change F24 labels from
`Published Expression: Ein feste Burg ist unser Gott`
to 
`Publication carrying: Ein feste Burg ist unser Gott`

**Comment by BergListe** [comment]
I hopefully fixed this issue.

Connected to this issue i found this label - is this the way it should look?

```
#F30 issue
<https://sk.acdh.oeaw.ac.at/DWbibl00687/publication> a frbroo:F30_Publication_Event ;
  rdfs:label "Publication of: Published Expression: Ein feste Burg ist unser Gott"@en ;
```

**Comment by BOberreither** [comment]
@BergListe Right - should be without "Published Expression: " in the middle ....

**Comment by BergListe** [comment]
Fixed this additional bug as well.

**Comment by BOberreither** [comment]
@BergListe  Looks good, but: Added an update up there, it concerns another group of F24s as well: those created not from title-j, title-m or date-keys, but from wholeText-citedRange. Thanks!

**Comment by BOberreither** [comment]
@BergListe Currently, the whole F24 for <https://sk.acdh.oeaw.ac.at/DWbibl00687> is missing, and everything connected to it (F30, time-span, etc.) – ?

**Comment by BergListe** [comment]
As mentioned in a comment to issue #26 i fixed the bug that excluded every statement with an uri coming from `bible/@xml:id`

**Comment by BOberreither** [comment]
@BergListe If the URI of an F24 is built from citedRange-wholeText, it should also be changed to "Publication carrying:"
For example this one should change:
```
<https://sk.acdh.oeaw.ac.at/DWbibl03133/published-expression> a frbroo:F24_Publication_Expression ;
  rdfs:label "Published Expression: Das 25-Punkte-Programm der Nationalsozialistischen Deutschen Arbeiterpartei"@en ;
  cidoc:P165_incorporates <https://sk.acdh.oeaw.ac.at/DWbibl03133> ;
  frbroo:R24i_was_created_through <https://sk.acdh.oeaw.ac.at/DWbibl03133/publication> .
```

**Comment by BergListe** [comment]
Done
