### ISSUE TITLE
Deleting some wholeperiodicals

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#26]
Right now, when there is a `citedRange[@wholePeriodical="yes"]`, an F24 is built from title j key; that's correct.

But also, an F24 is built from `bibl/@xml:id` and from `citedRange/@xml:id`, including respective F30, E52, F22, E42 statements. 
**IF** there is a `citedRange[@wholePeriodical="yes"]` in th bibl element, all these statements should not be built.

**Comment by BergListe** [comment]
Could you share an example, please?

**Comment by BOberreither** [comment]
@BergListe 
Sure:
### From title j key (correct):
```
    <https://sk.acdh.oeaw.ac.at/DWbibl04277/published-expression> a frbroo:F24_Publication_Expression ;
        rdfs:label "Periodical: Ostara"@en .
```
### From bibl xml:id (wrong):
```
<https://sk.acdh.oeaw.ac.at/DWbibl03236/publication> a frbroo:F30_Publication_Event ;
        rdfs:label "Publication of: Published Expression: "@en ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWbibl03236/publication/time-span> ;
        cidoc:P7_took_place_at sk:DWplace00085 ;
        cidoc:R24_created <https://sk.acdh.oeaw.ac.at/DWbibl03236/published-expression> .

    <https://sk.acdh.oeaw.ac.at/DWbibl03236/publication/time-span> a cidoc:E52_Time-Span ;
        rdfs:label "1905 - 1917"@en ;
        cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl03236/publication> ;
        cidoc:P82a_begin_of_the_begin "1905"^^xsd:gYear ;
        cidoc:P82b_end_of_the_end "1917"^^xsd:gYear .

    <https://sk.acdh.oeaw.ac.at/DWbibl03236/published-expression> a frbroo:F24_Publication_Expression ;
        rdfs:label "Published Expression: "@en ;
        cidoc:P165_incorporates sk:DWbibl03237 ;
        cidoc:P1_is_identified_by <https://sk.acdh.oeaw.ac.at/DWbibl03237/appellation/0> ;
        cidoc:R24i_was_created_through <https://sk.acdh.oeaw.ac.at/DWbibl03237/publication> .
```
Having F30 and E52 with the right URIs would be nice, but is not at the top of my priority list right now ...
### F22 from citedRange **wholePeriodical** (also wrong):
```
    sk:DWbibl03237 a frbroo:F22_Self-Contained_Expression ;
        rdfs:label "Expression: [Expression]"@en .
```

**Comment by BergListe** [comment]
> ... including respective F30, E52, F22, E42 statements.

I think, I fixed this issue but I didn't find a case of an oddly generated E42. If you stumble upon one please share.

**Comment by BOberreither** [comment]
@BergListe 
So, i found a bug - in my comment above: The last wrongly built statement including attached E42 and F28 is built not from wholeText citedRange, but from **wholePeriodical** citedRange. If there is one of these, don't create F22, E42 and F28 from it. The F22 is built from the title j key, and thats enough from a bibl containing a wholePeriodical.

**Comment by BergListe** [comment]
Now only items with `citedRange[@wholePeriodical="yes"]` are excluded from the creation of the above mentioned statements.
