### ISSUE TITLE
listbibl: INT3 - some wrong referred_to_entities

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#28]
Looks like this:
```
    <https://sk.acdh.oeaw.ac.at/DWbibl02002/relation/0> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity <https://sk.acdh.oeaw.ac.at/DWbibl03478/passage/0> ;
        ns1:R13_has_referring_entity sk:DWbibl02002 .
```
But should in some cases look like this:
```
    <https://sk.acdh.oeaw.ac.at/DWbibl02002/relation/0> a ns1:INT3_IntertextualRelationship ;
        rdfs:label "Intertextual relation"@en ;
        ns1:R12_has_referred_to_entity sk:DWbibl03478 ;
        ns1:R13_has_referring_entity sk:DWbibl02002 .
```
Look up if the `citedRange` element referred to in `ref type int` is itself a `wholeText`; if yes, do it like this (don't point the reference at a non-existing text passage).

Thanks!

**Comment by BergListe** [comment]
Fixed this and hopefully didn't introduce a new bug. It's getting a bit confusing now. I really hope to not have to go down this rabbit hole again 😢

**Comment by BOberreither** [comment]
@BergListe I feel the same.

**Comment by BOberreither** [comment]
@BergListe But it looks good.
