### ISSUE TITLE
Minor: One more Property for Segment's Pagination

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#32]
Segments carrying Text Passages and Segments carrying F22 have a has_location property like this: 
```
<https://sk.acdh.oeaw.ac.at/DWbibl02431/segment> a ns1:INT16_Segment ;
        rdfs:label "Segment: Eigene „Judenklasse“ auf der Reichsbahn"@en ;
        ns1:R16_incorporates sk:DWbibl02431 ;
        ns1:R25_is_segment_of <https://sk.acdh.oeaw.ac.at/DWbibl04523/published-expression> ;
        ns1:R41_has_location "S. 4"^^xsd:string .
```
(Last line.) Please add another line with the same value, just with another property: schema:pagination (namespace: <https://schema.org/>

**Comment by BergListe** [comment]
I found three statement types that contain `ns1:R41_has_location`:

- #INT1 textpassage
- #INT16 segment
- #INT1-INT16 textpassage segment

Should I add `schema:pagination` to all three of them?

**Comment by BOberreither** [comment]
@BergListe Only to the segments, so 
- Segments carrying whole F22s (I think they are called #INT16 segment), with the value from biblScope/text()
- Segments carrying INT1 Text passages (#INT1-INT16 textpassage segment), with the  from citedRange/text()

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe Thanks - one tiny thing: I think the segments for passages already had that? Anyway, there are two schama:pagination-triples in these statements. Please delete one – ideally the one without the data type xsd:string attached.

**Comment by BergListe** [comment]
Done
