### ISSUE TITLE
Minor: Wrong ID number in some Publication Time-Spans

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#33]
### DW texts
Looks like:
```
    <https://sk.acdh.oeaw.ac.at/DWbibl02018/publication/time-span> a cidoc:E52_Time-Span ;
        rdfs:label "1907"@en ;
        cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl02018/publication> ;
        cidoc:P82a_begin_of_the_begin "1907"^^xsd:gYear ;
        cidoc:P82b_end_of_the_end "1907"^^xsd:gYear .
```
Where there is a wholeText-citedRange, the ID number in the URI must be taken from this citedRange; in this case, it should be "DWbibl02019".

**Comment by BergListe** [comment]
This one is weird: I can't find the entry in dw_texts.ttl. Can it be that I removed this entry when I fixed the unwanted entires bug from issue #26 (Deleting some wholeperiodicals)?

**Comment by BergListe** [comment]
Part of the problem of missing statements is caused by issue #26 (section `F22 from citedRange wholetext`)

**Comment by BOberreither** [comment]
@BergListe I think you are right. The whole F24 and F30 and corresponding time spans disappeared. This is true for at least all "simple" F22s as well (with URIs built from the bibl's xml:id) .

**Comment by BergListe** [comment]
After today's changes the above mentioned entry re-appeared!

Is this the correct way this staement should look?

```
    <https://sk.acdh.oeaw.ac.at/DWbibl02018/publication/time-span> a cidoc:E52_Time-Span ;
        rdfs:label "1907"@en ;
        cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl02019/publication> ;
        cidoc:P82a_begin_of_the_begin "1907"^^xsd:gYear ;
        cidoc:P82b_end_of_the_end "1907"^^xsd:gYear .
```

**Comment by BOberreither** [comment]
Currently, it looks like this:
```
<https://sk.acdh.oeaw.ac.at/DWbibl02018/publication/time-span> a cidoc:E52_Time-Span ;
  rdfs:label "1907"@en ;
  cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl02018/publication> ;
  cidoc:P82a_begin_of_the_begin "1907"^^xsd:gYear ;
  cidoc:P82b_end_of_the_end "1907"^^xsd:gYear .
```
– with twice the wrong id, from bibl, not the wholeText-citedRange. But looks like it only concerns the E52 statements.

**Comment by BergListe** [comment]
so both occurences of  `DWbibl02018` in your example should be replaced with `DWbibl02019`?

**Comment by BOberreither** [comment]
Yup

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe Ok, one clarification: All this goes only when there actually is a time-span to be built. Sorry for the confusion.
So if there is no `title m key` and no `date key`, and the citedRange is a `wholeText`, then there is a time-span to be built from it.
Meaning: 
```
<https://sk.acdh.oeaw.ac.at/DWbibl02016/publication/time-span> a cidoc:E52_Time-Span ;
  rdfs:label "1933-05-25"@en ;
  cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl02016/publication> ;
  cidoc:P82a_begin_of_the_begin "1933-05-25"^^xsd:date ;
  cidoc:P82b_end_of_the_end "1933-05-25"^^xsd:date .
```
should not exist.
```
<https://sk.acdh.oeaw.ac.at/DWbibl02019/publication/time-span> a cidoc:E52_Time-Span ;
  rdfs:label "1907"@en ;
  cidoc:P4i_is_time-span_of <https://sk.acdh.oeaw.ac.at/DWbibl02019/publication> ;
  cidoc:P82a_begin_of_the_begin "1907"^^xsd:gYear ;
  cidoc:P82b_end_of_the_end "1907"^^xsd:gYear .
```
should (and it does).

**Comment by BergListe** [comment]
Oh this is a bit of an unexpected plot twist - I hope I did it right now.
