### ISSUE TITLE
text.ttl - refining some time-spans

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#36]
## 1. `date`-Elements with only `@notBefore`
These are being ignored right now, if I see this correctly. There is a time-span as an object in the F30_Publication_Event, but no statement for the timespan itself. The same with the time-spans linked to F28_Expression_Creation.
In these cases, please create a time-span as usual, just only use the `cidoc:P82a_begin_of_the_begin`. Don't use the `cidoc:P82b_end_of_the_end`.
Also add the line
`cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx> ;`
## 2. `date`-Elements with only `@notAfter`
Like above, just vice versa (use only `cidoc:P82b_end_of_the_end`).
## 3. Date Type "approx"
I thought we already had that, but maybe I was wrong; anyway: If a `date`-element has `@type="approx"`, please add this line to the time-span (like above):
`cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx> ;`

**Comment by BergListe** [comment]
I applied all three changes to the timespan elements.

**Comment by BOberreither** [comment]
@BergListe Nice! Some notes:
- [x] rdfs:label in these cases contains nothing; just take date/text()
- [x] date type approx goes with both the "onle-notBefore" and the "only-notAfter" cases.

**Comment by BergListe** [comment]
> date type approx goes with both the "onle-notBefore" and the "only-notAfter" cases.

yes, it should already work like this:

```xml
  <xsl:if test="tei:date[@type='approx']">
    <xsl:text>  cidoc:P2_has_type &lt;https://sk.acdh.oeaw.ac.at/types/date/approx&gt;</xsl:text>
  </xsl:if>
```

**Comment by BOberreither** [comment]
@BergListe To clarify: Not just the `@type="approx"`, but also the other two cases mentioned here need this type.

**Comment by BergListe** [comment]
oh, I overlooked this line in your initial statement

> Also add the line cidoc:P2_has_type <https://sk.acdh.oeaw.ac.at/types/date/approx> ;

**Comment by BOberreither** [comment]
@BergListe Some new bug? Now those with just notBefore and a F30 publication event have no publication time-span any more.

**Comment by BergListe** [comment]
Do you have an example bibl?

**Comment by BOberreither** [comment]
`<https://sk.acdh.oeaw.ac.at/DWbibl02259/publication/time-span>`
This occurs only as an object in the F30 statment, but has no own statement any more.

**Comment by BergListe** [comment]
Done

**Comment by BOberreither** [comment]
@BergListe 
Fine with just one remark:
If there is a citedRange wholeText, the E52 is built upon the citedRange ID; this is correct UNLESS there is a date key or a title m key; in these cases build the E52 based on these key values.
(The corresponding triple in the respective publication statements are fine, btw.)
Nearly done!

**Comment by BergListe** [comment]
How should the priority look like?

1. tei:date/@key
2. tei:title[@level='m']/@key
3. tei:citedRange/@xml_id

**Comment by BOberreither** [comment]
date-key, else title m key, else citedRange wholeText (else bibl ID)
