### ISSUE TITLE
dw sources

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#4]
@csae8092 had a script to replace the shortened sources with the longer versions in note @type="source" @subtype="publ"; some didn't work because the script couldn't match, since there were two or more short sources in the note element. These have now been split to two or more note elements. Pls run script again to replace those with longer versions, thanks!

**Comment by linxOD** [comment]
56819598852a0ff164d52724fca831bae451717b

**Comment by BOberreither** [comment]
@linxOD 
https://github.com/semantic-kraus/dw-data/commit/56819598852a0ff164d52724fca831bae451717b looks perfect!
