### ISSUE TITLE
A missing inverse property

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#45]
There seems to be no inverse of
<https://sk.acdh.oeaw.ac.at/DWbibl00000> <https://cidoc-crm.org/frbroo/sites/default/files/FRBR2.4-draft.rdfs#R17i_was_created_by> <https://sk.acdh.oeaw.ac.at/DWbibl00000/creation>

How's that?

**Comment by linxOD** [comment]
These are the triples I could find in data.trig:

    sk:DWbibl00000 a frbroo:F22_Self-Contained_Expression ;
        rdfs:label "Dritte Walpurgisnacht"@und ;
        cidoc:P102_has_title <https://sk.acdh.oeaw.ac.at/DWbibl00000/title/0> ;
        cidoc:P165i_is_incorporated_in <https://sk.acdh.oeaw.ac.at/DWbibl00000/published-expression> ;
        cidoc:P1_is_identified_by <https://sk.acdh.oeaw.ac.at/DWbibl00000/identifier/0>,
            <https://sk.acdh.oeaw.ac.at/DWbibl00000/identifier/1> ;
        frbroo:R17i_was_created_by <https://sk.acdh.oeaw.ac.at/DWbibl00000/creation> .

    sk:DWpers0000 a cidoc:E21_Person ;
        rdfs:label "Kraus, Karl"@und ;
        cidoc:P100i_died_in <https://sk.acdh.oeaw.ac.at/DWpers0000/death> ;
        cidoc:P14i_performed <https://sk.acdh.oeaw.ac.at/DWbibl00000/creation>,
            <https://sk.acdh.oeaw.ac.at/DWpers0000/occupation/01> ;
        cidoc:P1_is_identified_by <https://sk.acdh.oeaw.ac.at/DWpers0000/appellation/0>,
            <https://sk.acdh.oeaw.ac.at/DWpers0000/identifier/DWpers0000>,
            <https://sk.acdh.oeaw.ac.at/DWpers0000/identifier/idno/0>,
            <https://sk.acdh.oeaw.ac.at/DWpers0000/identifier/idno/1> ;
        cidoc:P98i_was_born <https://sk.acdh.oeaw.ac.at/DWpers0000/birth> .

    <https://sk.acdh.oeaw.ac.at/DWbibl00000/creation> a frbroo:F28_Expression_Creation ;
        rdfs:label "Creation of: Dritte Walpurgisnacht"@en ;
        cidoc:P14_carried_out_by sk:DWpers0000 ;
        cidoc:P4_has_time-span <https://sk.acdh.oeaw.ac.at/DWbibl00000/creation/time-span> ;
        frbroo:R17_created sk:DWbibl00000 .
