### ISSUE TITLE
Missing ID

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#50]
Polenlieder now has no ID at all, URI looks like "https://sk.acdh.oeaw.ac.at/"

(In a funny conicidence, this is the URI a couple of thousand of ghost Mentions from Die Fackel refer to ...)

**Comment by BergListe** [comment]
Here is an example that leads to an URI like "https://sk.acdh.oeaw.ac.at/":   

```xml
<bibl source="_" xml:id="DWbibl00425" sortKey="Platen_August_von">
  <author key="#DWpers0187">August von Platen</author>
  <title level="a">An einen deutschen Fürsten</title>
  <title level="m" key="#DWbibl04601">Polenlieder</title>
  <date when="1831">1831<note>Entst.</note></date>
  <citedRange xml:id="DWbibl00431">Strophe VII</citedRange><!-- Wie Mancher … Haß der Welt -->
</bibl>
```

The Xsl-Code looks like this - maybe an additional <xsl:when/> branch has to be added?

```xsl
    <xsl:variable name="uri">
      <xsl:choose>
        <xsl:when test="tei:title[@level = 'j']">
          <xsl:value-of select="tei:date/@key"/>
        </xsl:when>
        <xsl:when test="tei:title[@level = 'm']/@key and not(tei:date/tei:note/text() = 'Entst.')">
          <xsl:value-of select="tei:title[@level = 'm']/@key"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:text/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
```

**Comment by BOberreither** [comment]
I assume the variable "uri" is the one of the "incorporating F22" that incorporates the "original F22" of the bibl entry? The "original" getting its uri from bibl/xml:id or citedrange[wholeText]? 
(An example: "Polenlieder" being the "incorporating F22", "An einen deutschen Fürsten" being the "original F22".)
If this is the case, then we need to change 
`<xsl:when test="tei:title[@level = 'm']/@key and not(tei:date/tei:note/text() = 'Entst.')">`
to
`<xsl:when test="tei:title[@level = 'm']/@key">`
or at least add a new rule for the latter.
Because filtering for "Entst." makes no sense in this specific cases: This filter is only supposed to prevent the construction of an F24 publication Expression based on the "incorporating F22", as well as the publication events, time-spans etc. attached to it. That is all fine. But in the case of the bibl above, it shouldn't prevent the "incorporating F22" from being built. What we need is 
- [x] The "original F22" 
- [x] a creation event with 
- [x] author and 
- [x] "Entst."-time-span, 
--> all of which works perfectly right now. But we also need
- [ ] "incorporating F22" incorporating the "original F22"
- [ ] with a title
--> which are both to be based on the title-m-key.

To put it in xPath: All this concerns the handful of bibls you find with 
`//bibl[title[@level="m" and @key] and contains(date/note, "Entst.")]`

If you can give the "incorporating F22" its own author (just the one in parent::bibl/author), linked through its own creation event (no time-span here), that would be a nice bonus.

**Comment by BergListe** [comment]
is this the same problem that is covered in issue #43?
