### ISSUE TITLE
Strange one: pretty identical DW quotes treated differently ...

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#52]
This item from ...additional_info.xml is treated correctly:
```
<item>
        <id>DWquote2106</id>
        <permalink>https://kraus1933.ace.oeaw.ac.at/absatz_19#DWquote2106</permalink>
        <paragraph>absatz_19</paragraph>
        <source>#DWbibl04103</source>
        <type/>
        <content>in der man Gold dafür gab</content>
        <info source="DWbibl04103" wholeText="yes" wholePeriodical="no" posCitedRange="0" refInt="DWbibl04101" refIntSubtype="nonexcl" refLevel="no" refPos="0" refBase="DWbibl04100" refInt2="no" refIntSubtype2="no" refLevel2="no" refPos2="no" refBase2="no"/>
    </item>
```
The referred-to-entity is `https://sk.acdh.oeaw.ac.at/DWbibl04100/passage/0` (correct).

While this item and some others are treated wrongly:
```
<item>
        <id>DWquote0520</id>
        <permalink>https://kraus1933.ace.oeaw.ac.at/absatz_21#DWquote0520</permalink>
        <paragraph>absatz_21</paragraph>
        <source>#DWbibl00555</source>
        <type>exemp</type>
        <content>Ein gewisses Wissen aber, hauptsächlich um die Geschichte der Bewegung seit dem Reichstagsbrand, ermöglicht es ihm, allen Unbilden zum Trotz durchzuhalten.</content>
        <info source="DWbibl00555" wholeText="yes" wholePeriodical="no" posCitedRange="0" refInt="DWbibl03433" refIntSubtype="nonexcl" refLevel="no" refPos="0" refBase="DWbibl03432" refInt2="no" refIntSubtype2="no" refLevel2="no" refPos2="no" refBase2="no"/>
    </item>
```
Here, the referred to entity is `https://sk.acdh.oeaw.ac.at/DWbibl00555/passage/0`. So the base-ID is taken from `@source`, although there is a `@wholeText="yes"`. One correct version would be, like above, to take the base-ID from @refBase in these cases.

With the xPath`//info[@wholeText="yes" and @refInt!="no" and @refLevel="no"]` you can find the one correct and nine wrong items. Is there a specific rule for this xPath? If not, in which other rules are they treated  (and why in different ones)?

Anyway, don't push a new version of your xslt, let's first compare results of the current and a possible new transformation. So we don't add any bugs or delete stuff we need.

**Comment by BergListe** [comment]
> Anyway, don't push a new version of your xslt, let's first compare results of the current and a possible new transformation. So we don't add any bugs or delete stuff we need.

ok, let's do this together in the office.

**Comment by BergListe** [comment]
Added a new <xsl:when>.
