### ISSUE TITLE
dw listperson: finally, some events!

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/dw-data#6]
Some person entries don't have either birth or death elements, instead one or more event elements (representing their burials, gone missing, declaration of death etc.)

So, for each event element in person,
- [ ] create a cidoc E5_Event, URI: https://sk.acdh.oeaw.ac.at/[person-xml:id]/event/[n]
- [ ] create respective time-span, URI: https://sk.acdh.oeaw.ac.at/[person-xml:id]/event/[n]/time-span

- [ ] Then model like this:
```
<https://sk.acdh.oeaw.ac.at/[person-xml:id]/event/[n]> a ns1:E5_Event ;
rdfs:label "Event: [event/note/text()]" ;
ns1:P4_has_time-span <https://sk.acdh.oeaw.ac.at/[person-xml:id]/event/[n]/time-span> ;
ns1:P7_took_place_at <https://sk.acdh.oeaw.ac.at/[event/desc/placeName/substring-after(@key, "#")]> ;
ns1:P2_has_type <https://sk.acdh.oeaw.ac.at/types/event/[event/@type] .

<https://sk.acdh.oeaw.ac.at/[person-xml:id]/event/[n]/time-span> a ns1:E52_Time-Span ;
rdfs:label "event/desc/date/@when" ;
ns1:P82a_begin_of_the_begin "event/desc/date/@when"^^xsd:date ;
ns1:P82b_end_of_the_end "event/desc/date/@when"^^xsd:date .
```

**Comment by csae8092** [comment]
@linxOD just create a file e.g. extra_cidoc_utily.py (or whatever) in `scripts`, copy code from https://github.com/acdh-oeaw/acdh-cidoc-pyutils/blob/cde8558f5718e1e809dd196f67cd3f368eb29c46/acdh_cidoc_pyutils/__init__.py#L545 into this file (plus needed imports) and include the function in your script

see #https://github.com/acdh-oeaw/acdh-cidoc-pyutils/issues/63

**Comment by linxOD** [comment]
2528e55410581b21db925f7748efcc9a89977f5a and 9eeb441f8f0e32f52ed8e3399feb8b04aff7f6d8
